name: "frontify-url-minifier"
services:
  app:
    container_name: frontify-url-minifier
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # used by Caddy
      - SERVER_NAME=${SERVER_NAME:?set it in .env}
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: bash -c "[ -f /app/vendor/autoload.php ]"
      timeout: 10s
      retries: 30

networks:
  default:
    name: local
    external: true

volumes:
  caddy_data:
  caddy_config:
